baseURL = "https://alipullup.github.io/"
languageCode = "en-us"
title = "Ali's Posts"
theme = "hugo-PaperMod"
copyright = "This work is licensed under a Creative Commons Attribution 4.0 International License."
[taxonomies]
  tag = "tags"

